spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password: 1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

#logging.level:
  #org.hibernate.SQL: debug
  #org.hibernate.type: trace

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "974320703377-7mc4flmb4a84qh7l1j4nvgab4ts9b1n9.apps.googleusercontent.com"
            client-secret: "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"
            scope: profile, email